contents:
  repositories:
    - https://packages.cgr.dev/extras
  keyring:
    - https://packages.cgr.dev/extras/chainguard-extras.rsa.pub
  packages:
    - bash-completion
    - ca-certificates-bundle
    - chainctl
    - wolfi-baselayout
    - sdk
    - grype
    - apk-tools
    - gcsfuse
    - gitsign
    - spdx-tools-java

environment:
  COLORTERM: truecolor
  TERM: xterm-256color

entrypoint:
  command: /usr/bin/sdk
