on:
  pull_request:

permissions:
  contents: read # Needed to clone the repo

jobs:
  alpine-base:
    uses: ./.github/workflows/.build.yaml
    with:
      image: alpine-base

  gcc-musl:
    uses: ./.github/workflows/.build.yaml
    with:
      image: gcc-musl

  musl-dynamic:
    uses: ./.github/workflows/.build.yaml
    with:
      image: musl-dynamic

  sdk:
    uses: ./.github/workflows/.build.yaml
    with:
      image: sdk
      melange-config: configs/latest.melange.yaml

  static-alpine:
    uses: ./.github/workflows/.build.yaml
    with:
      image: static

  git-alpine:
    uses: ./.github/workflows/.build.yaml
    with:
      image: git

  busybox-alpine:
    uses: ./.github/workflows/.build.yaml
    with:
      image: busybox
