on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

concurrency: release

permissions:
  contents: read  # Needed to clone the repo
  id-token: write # Needed to sign images
  packages: write # Needed to publish images to GHCR

jobs:
  alpine-base:
    uses: ./.github/workflows/.build.yaml
    with:
      image: alpine-base
      registry: ghcr.io/wolfi-dev

  gcc-musl:
    uses: ./.github/workflows/.build.yaml
    with:
      image: gcc-musl
      registry: ghcr.io/wolfi-dev

  musl-dynamic:
    uses: ./.github/workflows/.build.yaml
    with:
      image: musl-dynamic
      registry: ghcr.io/wolfi-dev

  sdk:
    uses: ./.github/workflows/.build.yaml
    with:
      image: sdk
      melange-config: configs/latest.melange.yaml
      registry: ghcr.io/wolfi-dev

  static-alpine:
    uses: ./.github/workflows/.build.yaml
    with:
      image: static
      registry: ghcr.io/wolfi-dev

  git-alpine:
    uses: ./.github/workflows/.build.yaml
    with:
      image: git
      registry: ghcr.io/wolfi-dev

  busybox-alpine:
    uses: ./.github/workflows/.build.yaml
    with:
      image: busybox
      registry: ghcr.io/wolfi-dev
